version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - ./gradlew test #TODO: add parameters in new task
  post_build:
    commands:
      - echo "post_build step"
artifacts:
  files:
    - '**/*'
