version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - java -jar karate.jar tests
  post_build:
    commands:
      - echo "post_build step"
artifacts:
  files:
    - "**/*"
