name: E2E Test

on: [push, pull_request]

jobs:
  Gherkin-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: restqa/gherkin-linter-action@0.0.1
      with:
        path: 'src/test/java/tests'
        config_file: '.gherkin-lintrc'
